### ISSUE TITLE
installing error

### ISSUE THREAD

**Issue by brabant-v** [yaacov/node-modbus-ws#1]
I simply can't seem to get this package installed on my raspberry pi.
I've tried so many different ways to install thisbut none seem to work.
As a sudo or root I don't have acces to "/root/.node-gyp/4.2.1"
When I download the zip file i get untarring error.

pi@raspberrypi:~ $ npm install modbus-ws -g
npm ERR! tar.unpack untar error /home/pi/.npm/modbus-ws/2.1.2/package.tgz
npm ERR! Linux 4.1.17-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "modbus-ws" "-g"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! path /usr/local/lib/node_modules/modbus-ws
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/modbus-ws'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/modbus-ws']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/modbus-ws',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/modbus-ws',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack:
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

**npm-debug.log**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'modbus-ws',
1 verbose cli   '-g' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'modbus-ws', null ]
7 verbose cache add spec modbus-ws
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'modbus-ws',
8 silly cache add   scope: null,
8 silly cache add   name: 'modbus-ws',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '_',
8 silly cache add   type: 'range' }
9 silly addNamed modbus-ws@_
10 verbose addNamed "_" is a valid semver range for modbus-ws
11 silly addNameRange { name: 'modbus-ws', range: '_', hasData: false }
12 silly mapToRegistry name modbus-ws
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/modbus-ws
16 verbose addNameRange registry:https://registry.npmjs.org/modbus-ws not in flight; fetching
17 verbose request uri https://registry.npmjs.org/modbus-ws
18 verbose request no auth needed
19 info attempt registry request try #1 at 09:42:01
20 verbose request id be5416f8a9452122
21 verbose etag "CM3OHW8L26WDP7HOJD416I4XX"
22 http request GET https://registry.npmjs.org/modbus-ws
23 http 304 https://registry.npmjs.org/modbus-ws
24 verbose headers { date: 'Thu, 03 Mar 2016 09:42:02 GMT',
24 verbose headers   via: '1.1 varnish',
24 verbose headers   'cache-control': 'max-age=300',
24 verbose headers   etag: '"CM3OHW8L26WDP7HOJD416I4XX"',
24 verbose headers   age: '0',
24 verbose headers   connection: 'keep-alive',
24 verbose headers   'x-served-by': 'cache-lhr6328-LHR',
24 verbose headers   'x-cache': 'MISS',
24 verbose headers   'x-cache-hits': '0',
24 verbose headers   'x-timer': 'S1456998122.064820,VS0,VE316',
24 verbose headers   vary: 'Accept' }
25 silly get cb [ 304,
25 silly get   { date: 'Thu, 03 Mar 2016 09:42:02 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     'cache-control': 'max-age=300',
25 silly get     etag: '"CM3OHW8L26WDP7HOJD416I4XX"',
25 silly get     age: '0',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-lhr6328-LHR',
25 silly get     'x-cache': 'MISS',
25 silly get     'x-cache-hits': '0',
25 silly get     'x-timer': 'S1456998122.064820,VS0,VE316',
25 silly get     vary: 'Accept' } ]
26 verbose etag https://registry.npmjs.org/modbus-ws from cache
27 verbose get saving modbus-ws to /home/pi/.npm/registry.npmjs.org/modbus-ws/.cache.json
28 silly addNameRange number 2 { name: 'modbus-ws', range: '_', hasData: true }
29 silly addNameRange versions [ 'modbus-ws',
29 silly addNameRange   [ '1.0.0',
29 silly addNameRange     '1.0.1',
29 silly addNameRange     '1.1.1',
29 silly addNameRange     '1.1.2',
29 silly addNameRange     '1.2.2',
29 silly addNameRange     '1.3.2',
29 silly addNameRange     '1.3.4',
29 silly addNameRange     '1.9.4',
29 silly addNameRange     '1.99.0',
29 silly addNameRange     '2.0.1',
29 silly addNameRange     '2.0.2',
29 silly addNameRange     '2.1.2' ] ]
30 silly addNamed modbus-ws@2.1.2
31 verbose addNamed "2.1.2" is a plain semver version for modbus-ws
32 silly cache afterAdd modbus-ws@2.1.2
33 verbose afterAdd /home/pi/.npm/modbus-ws/2.1.2/package/package.json not in flight; writing
34 verbose afterAdd /home/pi/.npm/modbus-ws/2.1.2/package/package.json written
35 silly install resolved [ { name: 'modbus-ws',
35 silly install resolved     version: '2.1.2',
35 silly install resolved     description: 'NodeJS Modbus to WebSocket bridge',
35 silly install resolved     main: 'index.js',
35 silly install resolved     bin: { 'modbus-ws': './bin/modbus-ws.js' },
35 silly install resolved     scripts: { start: 'node ./bin/modbus-ws.js', test: 'mocha' },
35 silly install resolved     repository:
35 silly install resolved      { type: 'git',
35 silly install resolved        url: 'git+https://github.com/yaacov/node-modbus-ws.git' },
35 silly install resolved     keywords: [ 'modbus', 'websocket', 'socket.io', 'server' ],
35 silly install resolved     author: { name: 'Yaacov Zamir', email: 'kobi.zamir@gmail.com' },
35 silly install resolved     license: 'ISC',
35 silly install resolved     bugs: { url: 'https://github.com/yaacov/node-modbus-ws/issues' },
35 silly install resolved     homepage: 'https://github.com/yaacov/node-modbus-ws#readme',
35 silly install resolved     dependencies:
35 silly install resolved      { commander: '^2.9.0',
35 silly install resolved        ejs: '^2.3.4',
35 silly install resolved        express: '^4.13.3',
35 silly install resolved        'modbus-serial': '^1.3.2',
35 silly install resolved        serialport: '^2.0.5',
35 silly install resolved        'socket.io': '^1.3.7',
35 silly install resolved        sqlite3: '^3.1.1' },
35 silly install resolved     devDependencies: { chai: '^3.4.1', mocha: '^2.3.3', 'socket.io-client': '^1.3.7' },
35 silly install resolved     gitHead: 'e82b5e6cc16c543fd564566a57fd59dee672fafe',
35 silly install resolved     _id: 'modbus-ws@2.1.2',
35 silly install resolved     _shasum: 'a67269b25c642b0fcb89473bfdbf6c225fc3d833',
35 silly install resolved     _from: 'modbus-ws@_',
35 silly install resolved     _npmVersion: '1.4.21',
35 silly install resolved     _npmUser: { name: 'kzamir', email: 'yaacov.npm@gmail.com' },
35 silly install resolved     maintainers: [ [Object] ],
35 silly install resolved     dist:
35 silly install resolved      { shasum: 'a67269b25c642b0fcb89473bfdbf6c225fc3d833',
35 silly install resolved        tarball: 'http://registry.npmjs.org/modbus-ws/-/modbus-ws-2.1.2.tgz' },
35 silly install resolved     directories: {},
35 silly install resolved     _resolved: 'https://registry.npmjs.org/modbus-ws/-/modbus-ws-2.1.2.tgz',
35 silly install resolved     readme: 'ERROR: No README data found!' } ]
36 info install modbus-ws@2.1.2 into /usr/local/lib
37 info installOne modbus-ws@2.1.2
38 verbose installOne of modbus-ws to /usr/local/lib not in flight; installing
39 verbose lock using /home/pi/.npm/_locks/modbus-ws-0a20635a98992245.lock for /usr/local/lib/node_modules/modbus-ws
40 silly install write writing modbus-ws 2.1.2 to /usr/local/lib/node_modules/modbus-ws
41 verbose unbuild lib/node_modules/modbus-ws
42 silly gentlyRm /usr/local/lib/node_modules/modbus-ws is being purged from base /usr/local
43 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/modbus-ws
44 verbose tar unpack /home/pi/.npm/modbus-ws/2.1.2/package.tgz
45 verbose tar unpacking to /usr/local/lib/node_modules/modbus-ws
46 silly gentlyRm /usr/local/lib/node_modules/modbus-ws is being purged
47 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/modbus-ws
48 silly gunzTarPerm modes [ '755', '644' ]
49 error tar.unpack untar error /home/pi/.npm/modbus-ws/2.1.2/package.tgz
50 verbose unlock done using /home/pi/.npm/_locks/modbus-ws-0a20635a98992245.lock for /usr/local/lib/node_modules/modbus-ws
51 verbose fstream_path /usr/local/lib/node_modules/modbus-ws
52 verbose fstream_type Directory
53 verbose fstream_class DirWriter
54 verbose stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/modbus-ws'
54 verbose stack     at Error (native)
55 verbose fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25
55 verbose fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53
55 verbose fstream_stack FSReqWrap.oncomplete (fs.js:82:15)
56 verbose cwd /home/pi
57 error Linux 4.1.17-v7+
58 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "modbus-ws" "-g"
59 error node v4.2.1
60 error npm  v2.14.7
61 error path /usr/local/lib/node_modules/modbus-ws
62 error code EACCES
63 error errno -13
64 error syscall mkdir
65 error Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/modbus-ws'
65 error     at Error (native)
65 error  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/modbus-ws']
65 error   errno: -13,
65 error   code: 'EACCES',
65 error   syscall: 'mkdir',
65 error   path: '/usr/local/lib/node_modules/modbus-ws',
65 error   fstream_type: 'Directory',
65 error   fstream_path: '/usr/local/lib/node_modules/modbus-ws',
65 error   fstream_class: 'DirWriter',
65 error   fstream_stack:
65 error    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
65 error      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
65 error      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
66 error Please try running this command again as root/Administrator.
67 verbose exit [ -13, true ]
68 verbose unbuild lib/node_modules/modbus-ws
69 silly gentlyRm /usr/local/lib/node_modules/modbus-ws is being purged from base /usr/local
70 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/modbus-ws

**Comment by brabant-v** [comment]
fixed it with npm install --unsafe-prem modbus-ws

**Comment by yaacov** [comment]
Thanks, can you fix the how to install in the README and make a pull-request ?

**Comment by yaacov** [comment]
Fixed by: https://github.com/yaacov/node-modbus-ws/pull/2
