### ISSUE TITLE
problem with serialport rtu modbus readHoldingRegisters

### ISSUE THREAD

**Issue by cpfarher** [yaacov/node-modbus-ws#14]
Hello, I try to use the modbus ws server with the example, reading holding registers...  Modbus Ws server works ok, but I never received response on the client:
This is the client file: https://gist.github.com/cpfarher/81661f31eb0d85cd3a5782a2a8729b42
I check that ModbusRTU.prototype.writeFC4 never return next function? It read from modbus but never get the callback to the https://gist.github.com/cpfarher/81661f31eb0d85cd3a5782a2a8729b42#file-websocket-client-html-L83

**Comment by yaacov** [comment]
Thanks for the issue !
I will look into it, if you find the problem please comment here or open a pull request with the fix.

**Comment by yaacov** [comment]
@cpfarher  hi, sorry for the late response ...
your example works for me, what am I missing ?

![peek 2018-08-16 11-44](https://user-images.githubusercontent.com/2181522/44198328-c97e9200-a149-11e8-8da1-24ce5ee3e73b.gif)

**Comment by cpfarher** [comment]
your hello.html is the same as https://gist.github.com/cpfarher/81661f31eb0d85cd3a5782a2a8729b42 ?
node version?

**Comment by yaacov** [comment]
Yse, you can briefly see in the the attached gif whet it hits `debugger`

**Comment by yaacov** [comment]
p.s. how does the example in 
https://github.com/yaacov/node-modbus-ws/blob/master/examples/example.html
works for you ?
It looks very similar.

**Comment by cpfarher** [comment]
I forget to mention: with npm run-script start all works fine, but the problem whas with:
node ./bin/modbus-ws.js -s /dev/ttyACM0 -b 19200

**Comment by yaacov** [comment]
> the problem whas with:
node ./bin/modbus-ws.js -s /dev/ttyACM0 -b 19200

Thanks, will look into it :+1:

**Comment by yaacov** [comment]
@cpfarher any news ?

**Comment by cpfarher** [comment]
> @cpfarher any news ?

nop :-1: .... The project is on stand by for a long time...

**Comment by yaacov** [comment]
@cpfarher thanks, have fun with new projects :-)

Don't feel obligated, Just doing belated new-year cleanups and re-visiting stuff I didn't have time to look after.

**Comment by yaacov** [comment]
Closing stale issue
