### ISSUE TITLE
Connection via serial server

### ISSUE THREAD

**Issue by gz0000** [yaacov/node-modbus-ws#15]
Hello!

Does modbus-ws support raw TCP connection to serial server? I did some testing, but I was not successful. 

Best regards,
Gregor

**Comment by yaacov** [comment]
No, it supports serial or TCP not raw TCP.

p.s.
Should work with current libs, but didn't test it last 6 months ...
https://github.com/yaacov/node-modbus-ws/blob/master/package.json
