### ISSUE TITLE
Port not open error node >10

### ISSUE THREAD

**Issue by vadymvoitko** [yaacov/node-modbus-ws#17]
Greetings!
I'm trying to use this command 

modbus-ws -i 192.168.0.129:443

and connect to serial TCP from client with socket.io (2.1.11 or 2.3)
but it keeps emiting error on socket claiming "port not open" though the connection establishes and polling looks ok (never had experience with modbus though). I tried on node versions 10.16.0 (MacOS) and 12.16.2 (Win 10) - same result. I attached index.txt (couldn't html) - nothing fancy just was playing with different listeners. 

Please point out where am I wrong. I want to establish connection with modbus-serial attached to same port to check that data exchange between two clients is ok but modbus-serial also not working for me. Maybe its node version or maybe I'm doing smth wrong. Thanks

[index.txt](https://github.com/yaacov/node-modbus-ws/files/4671228/index.txt)

**Comment by yaacov** [comment]
Hi, thanks you for the issue !

> Maybe its node version or maybe I'm doing something wrong

Hmm, this code is very old,  It may be that the libraries used here are too old and the code need
to refresh and update it's dependencies.

a - If you find how to fix the problem, please comment here, 
b - I also labelled this as "help wanted" in case someone know how to fix it and can help.

**Comment by yaacov** [comment]
Closing stale issue
