### ISSUE TITLE
does 'writeCoil' or 'writeRegisters' conflict with polling? 

### ISSUE THREAD

**Issue by postgetme** [yaacov/node-modbus-ws#3]
what if at the time of receive 'fc1' data, then send a 'fc5' command?  I think it will cause error response frame, am i understand right?

**Comment by yaacov** [comment]
Hi, thanks for the question.

1 With modbus RTU protocol you require to wait for silence [1] on the line before sending new commands, to prevent this conflict.

2 With modbus TCP you use Transaction identifier [2] to identify each command-response pair, to prevent this conflict.

[1][2 ]https://en.wikipedia.org/wiki/Modbus#Frame_format

**Comment by postgetme** [comment]
thanks for your reply.

With modbus RTU protocol, if only run the polling progress, there is no problem, because the polling interval can keep the line silence between frames. But in practice, the 'writeCoil' or 'writeRegisters' command will come at any time in the polling time, that means it's hard to keep the line silence between frames.

**Comment by yaacov** [comment]
The modbus protocol forbid this situation [1], only one request/answer (read or write) comunication can be done on the serial line at single time.
You must synchronize the write command with the polling:
When writing on the serial line, all polling must stop and wait for write to finish, and then continue with pollinjg.

[1] https://en.wikipedia.org/wiki/Duplex_(telecommunications)#Half-duplex

**Comment by postgetme** [comment]
but I can't in the client side(in browser) synchronize the write command with the polling.

```
// server start
modbus-ws -s /dev/ttyUSB0

// polling
socket.emit("readHoldingRegisters", {
    "unit": 1,
    "address": 0,
    "length": 10,
    "interval": 1000
});

// this will trigger by a button at any time 
socket.emit('writeCoil', {
    "unit": 1,
    "address": 8,
    "state": true
});
```

i think the server side should have a mechanism to synchronize the write command with the polling, so that in the client side don't need to worry about the 'read write conflict' problem.

**Comment by yaacov** [comment]
I didn't think about this scenario :+1: 

Can you implement a muetx that will prevent read calls if a write call is waiting for an answer (with some default timeout) ?

Workaround: do the polling timer on the client side, where you control the requests timing.

**Comment by postgetme** [comment]
sorry, I'm afraid of I don't have the ability to implement it, my coding skill is pool. -_- !
I just read your code for study, and then come up with the problem.

**Comment by yaacov** [comment]
np :-)
